create table user(
    UserName varchar(250),
    FatherOrHusbandName varchar(250),
    DateOfBirth DATE,
    PhoneNumber varchar(100),
    Nationality varchar(250),
    PermanentAddress varchar(250),
    TemporaryAddress varchar(50),
    UIDNo varchar(50),
    PassportNo varchar(50),
    DateOfIssue DATE,
    PlaceOfIssue varchar(250),
    IDType varchar(250),
    IDNumber varchar(250),
    Occupation varchar(250),
    PropertyCategory varchar(250),
    PropertyType varchar(250),
    DescriptionOfProperty varchar(250),
      TotleValueOfProperty varchar(250),
      ValueOfProperty varchar(250),
      OccurenceDay DATE,
      OccurenceDateFrom DATE,
      OccurenceDateTo DATE,
      OccurenceTimePeriod TIME,
      OccurenceTimeFrom TIME,
      OccurenceTimeTo TIME,
      OccurenceDate DATE,
      OccurenceTime TIME,
      Occurence varchar(250),
      Accused varchar(250),
      FirstInformationcontent varchar(250),
      ReasonOfDelay varchar(250),
    UNIQUE(UIDNo)

);

 INSERT INTO user (
    UserName,
    FatherOrHusbandName,
    DateOfBirth,
    PhoneNumber,
    Nationality,
    PermanentAddress,
    TemporaryAddress,
    UIDNo,
    PassportNo,
    DateOfIssue,
    PlaceOfIssue,
    IDType,
    IDNumber,
    Occupation,
    PropertyCategory,
    PropertyType,
    DescriptionOfProperty,
    TotleValueOfProperty,
    ValueOfProperty,
    OccurenceDay,
    OccurenceDateFrom,
    OccurenceDateTo,
    OccurenceTimePeriod,
    OccurenceTimeFrom,
    OccurenceTimeTo,
    OccurenceDate,
    OccurenceTime,
    Occurence,
    Accused,
    FirstInformationcontent,
    ReasonOfDelay
) 
VALUES (
    'John Doe',                       
    'Richard Doe',                    
    '1980-05-15',                     
    '1234567890',                     
    'American',                       
    '123 Main St, City',             
    '456 Second St, City',            
    'A123456789',                     
    'P987654321',                     
    '2020-01-15',                     
    'New York',                    
    'Driver License',              
    'D987654321',                     
    'Engineer',                       
    'Residential',                   
    'Apartment',                      
    '2BHK apartment',                 
    '500000',                        
    '300000',                       
    '2024-10-10',                    
    '2024-10-01',                
    '2024-10-10',                 
    '12:00:00',                    
    '08:00:00',                     
    '11:00:00',                       
    '2024-10-10',                   
    '10:30:00',                       
    'Burglary',                      
    'John Smith',                  
    'Detailed description of incident.', 
    'No delay'                      
);

create table pdf (
    id int NOT NULL AUTO_INCREMENT,
    uuid varchar(200) NOT NULL,
    UserName varchar(250),
    FatherOrHusbandName varchar(250),
    DateOfBirth DATE,
    PhoneNumber varchar(100),
    Nationality varchar(250),
    PermanentAddress varchar(250),
    TemporaryAddress varchar(50),
    UIDNo varchar(50),
    PassportNo varchar(50),
    DateOfIssue DATE,
    PlaceOfIssue varchar(250),
    IDType varchar(250),
    IDNumber varchar(250),
    Occupation varchar(250),
    PropertyCategory varchar(250),
    PropertyType varchar(250),
    DescriptionOfProperty varchar(250),
    TotleValueOfProperty varchar(250),
    ValueOfProperty varchar(250),
    OccurenceDay DATE,
    OccurenceDateFrom DATE,
    OccurenceDateTo DATE,
    OccurenceTimePeriod TIME,
    OccurenceTimeFrom TIME,
    OccurenceTimeTo TIME,
    OccurenceDate DATE,
    OccurenceTime TIME,
    Occurence varchar(250),
    Accused varchar(250),
    FirstInformationcontent varchar(250),
    ReasonOfDelay varchar(250),
    primary key(id)
);

create table report (
    UserName varchar(250),
    FatherOrHusbandName varchar(250),
    DateOfBirth DATE,
    PhoneNumber varchar(100),
    Nationality varchar(250),
    PermanentAddress varchar(250),
    TemporaryAddress varchar(50),
    UIDNo varchar(50),
    PassportNo varchar(50),
    DateOfIssue DATE,
    PlaceOfIssue varchar(250),
    IDType varchar(250),
    IDNumber varchar(250),
    Occupation varchar(250),
    PropertyCategory varchar(250),
    PropertyType varchar(250),
    DescriptionOfProperty varchar(250),
    TotleValueOfProperty varchar(250),
    ValueOfProperty varchar(250),
    OccurenceDay DATE,
    OccurenceDateFrom DATE,
    OccurenceDateTo DATE,
    OccurenceTimePeriod TIME,
    OccurenceTimeFrom TIME,
    OccurenceTimeTo TIME,
    OccurenceDate DATE,
    OccurenceTime TIME,
    Occurence varchar(250),
    Accused varchar(250),
    FirstInformationcontent varchar(250),
    ReasonOfDelay varchar(250)
    
);

create table signupdata (
   id int primary key AUTO_INCREMENT,
   Name varchar(250),
   Email    varchar(250),
   UserRole varchar(250),
   password varchar(250) ,
   UNIQUE (Email)
);

create table complainantdata (
   id int primary key AUTO_INCREMENT,
   Name varchar(250),
   Email varchar(250),
   PhoneNumber varchar(50),
   password varchar(250) ,
   UNIQUE (Email)
);

create table policedata (
   id int primary key AUTO_INCREMENT,
   Name varchar(250),
   Email varchar(250),
   PhoneNumber varchar(50),
   PoliceOfficerRank varchar(250),
   PoliceOfficerId varchar(250),
   PoliceStationId varchar(250),
   password varchar(250) ,
   UNIQUE (Email)
);

create table complaintdetails (
    ComplaintId int ,
    ComplainantId int,
    PlaceOfOccurance varchar(250),
    Greviance varchar(250)
);